"""Tests for the enrichment core (prompt loading, parsing, lock, settings,
markdown render). Live Ollama calls are mocked."""
from __future__ import annotations

import asyncio
import json
from pathlib import Path
from unittest.mock import AsyncMock, patch

import pytest

from app import enrich
from app import enrich_lock
from app.enrich_md import render_enrich_md


def test_prompts_loaded_have_all_13_patterns():
    keys = set(enrich.PROMPTS)
    for key in enrich.DEFAULT_PATTERN_ORDER:
        assert key in keys, f"missing prompt for {key}"


def test_prompt_has_required_fields():
    # `named_entities` and `quotes` intentionally preserve native script
    # regardless of transcript language, so neither prompt carries the
    # {language_name} placeholder.
    # Sentiment uses a fixed English label set; named_entities and quotes
    # preserve native script; none carry a {language_name} placeholder.
    NO_LANG = {"named_entities", "quotes", "sentiment"}
    for key, meta in enrich.PROMPTS.items():
        assert meta["key"] == key
        assert meta["description"], f"{key} missing description"
        assert "{transcript_text}" in meta["body"], f"{key} missing transcript placeholder"
        if key not in NO_LANG:
            assert "{language_name}" in meta["body"], f"{key} missing language placeholder"


def test_language_name_known_codes():
    assert enrich.language_name("uk") == "Ukrainian"
    assert enrich.language_name("ru") == "Russian"
    assert enrich.language_name("en") == "English"
    assert "same language" in enrich.language_name("")


def test_parse_pattern_response_keyed():
    obj = enrich._parse_pattern_response("title", json.dumps({"title": "Hello"}))
    assert obj == "Hello"


def test_parse_pattern_response_unkeyed_singleton():
    # Some models return a single-key dict with a different name
    obj = enrich._parse_pattern_response("title", json.dumps({"x": "Hi"}))
    assert obj == "Hi"


def test_parse_pattern_response_empty_falls_back():
    obj = enrich._parse_pattern_response("main_ideas", "garbage not json")
    assert obj == []


def test_transcript_sha256_stable():
    payload = {"segments": [{"text": "a"}, {"text": "b"}]}
    s1 = enrich._transcript_sha256(payload)
    s2 = enrich._transcript_sha256(payload)
    assert s1 == s2
    payload2 = {"segments": [{"text": "a"}, {"text": "different"}]}
    assert s1 != enrich._transcript_sha256(payload2)


def test_load_enabled_patterns_default(tmp_settings):
    enabled = enrich.load_enabled_patterns(tmp_settings)
    assert enrich.EMBEDDING_KEY in enabled
    for key in enrich.DEFAULT_PATTERN_ORDER:
        assert key in enabled


def test_save_and_load_enabled_patterns_roundtrip(tmp_settings, tmp_path):
    tmp_settings.enrich_settings_path = tmp_path / "enrich-settings.json"
    enrich.save_enabled_patterns({"title", "summary"}, tmp_settings)
    enabled = enrich.load_enabled_patterns(tmp_settings)
    assert enabled == {"title", "summary"}


def test_render_md_minimal_section_ordering():
    sidecar = {
        "patterns": {
            "title": "Hello",
            "summary_tldr": "One line",
            "summary": "Para.",
            "main_ideas": ["a", "b"],
            "todos": [{"who": "spk_0", "what": "do thing", "anchor_sec": 12.5}],
            "hashtags": ["#tag"],
        },
        "model": "qwen2.5:7b",
        "ran_at": "2026-05-20T00:00:00Z",
        "transcript_sha256": "deadbeef",
    }
    md = render_enrich_md(sidecar, with_timecodes=False)
    # Section order
    i_title = md.index("# Hello")
    i_summary = md.index("## Summary")
    i_ideas = md.index("## Main Ideas")
    i_todos = md.index("## Todos")
    assert i_title < i_summary < i_ideas < i_todos
    # No timecode prefix in prose mode
    assert "[00:00:12]" not in md


def test_render_md_with_timecodes_adds_ts_prefix():
    sidecar = {
        "patterns": {
            "todos": [{"who": "spk_0", "what": "do thing", "anchor_sec": 12.5}],
            "quotes": [{"text": "nice", "speaker": "spk_0", "anchor_sec": 42.0}],
        },
        "model": "qwen2.5:7b",
        "ran_at": "x",
        "transcript_sha256": "deadbeef",
    }
    md = render_enrich_md(sidecar, with_timecodes=True)
    assert "[00:00:12]" in md
    assert "[00:00:42]" in md


def test_render_md_empty_sidecar_safe():
    md = render_enrich_md({"patterns": {}, "model": "?", "ran_at": "?",
                           "transcript_sha256": ""})
    # No crash; should contain the footer
    assert "<!-- Generated by webuiwhisper enrich" in md


@pytest.mark.asyncio
async def test_enrich_lock_serialises():
    """Two tasks waiting on the lock run one-after-another, never concurrently."""
    state = {"running": 0, "max_concurrent": 0}

    async def job(name: str):
        async with enrich_lock.acquire(name):
            state["running"] += 1
            state["max_concurrent"] = max(state["max_concurrent"], state["running"])
            await asyncio.sleep(0.03)
            state["running"] -= 1

    await asyncio.gather(job("a"), job("b"), job("c"))
    assert state["max_concurrent"] == 1


@pytest.mark.asyncio
async def test_enrich_runs_patterns_with_mocked_ollama(tmp_settings):
    """End-to-end: enrich() drives the patterns and returns a sidecar dict."""
    payload = {
        "language": "en",
        "segments": [
            {"speaker": "spk_0", "start_time": "00:00:00.000",
             "start_sec": 0.0, "end_sec": 5.0,
             "text": "We will ship Tuesday."},
        ],
    }

    async def fake_chat(self, prompt, json_mode=True):
        # Each pattern responds with a minimal JSON envelope.
        return json.dumps({"title": "Demo"})

    async def fake_embed(self, text):
        return [0.1, 0.2, 0.3]

    with patch.object(enrich.OllamaClient, "chat", new=fake_chat), \
         patch.object(enrich.OllamaClient, "embeddings", new=fake_embed):
        sidecar = await enrich.enrich(
            payload,
            enabled={"title", enrich.EMBEDDING_KEY},
            model="qwen2.5:7b",
            embed_model="nomic-embed-text",
            settings=tmp_settings,
            source_filename="demo.wav",
        )

    assert sidecar["patterns"]["title"] == "Demo"
    assert sidecar["embedding"]["whole"] == [0.1, 0.2, 0.3]
    assert sidecar["transcript_sha256"]
    assert sidecar["model"] == "qwen2.5:7b"


@pytest.mark.asyncio
async def test_enrich_records_failures_per_pattern(tmp_settings):
    payload = {"language": "en", "segments": [{"text": "x", "start_sec": 0}]}
    call_count = {"n": 0}

    async def flaky_chat(self, prompt, json_mode=True):
        call_count["n"] += 1
        if call_count["n"] == 1:
            raise enrich.OllamaError("boom")
        return json.dumps({"summary_tldr": "ok"})

    with patch.object(enrich.OllamaClient, "chat", new=flaky_chat):
        sidecar = await enrich.enrich(
            payload,
            enabled={"title", "summary_tldr"},
            model="qwen2.5:7b",
            embed_model="nomic-embed-text",
            settings=tmp_settings,
            source_filename="demo.wav",
        )

    assert "title" in sidecar["failures"]
    assert sidecar["patterns"]["summary_tldr"] == "ok"
